spring.application.name=LLMmemory
server.port=8081

# 1. Set your API Key
spring.ai.google.genai.api-key=${Gemini_API_KEY}

# 2. Specify the model
spring.ai.google.genai.chat.model=gemini-2.5-flash

# 3. Optional: Set temperature for response creativity
spring.ai.google.genai.chat.temperature=0.5   

#============================
# mysql
#============================
spring.datasource.url=jdbc:mysql://localhost:3307/Spring-Ai?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# this configuration automatically save all the chats in database instead of ConcurrentHashmap
# this directly connect chatMemoryRepository to jdbcChatMemoryRepository
spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS