spring.application.name=RAG
server.port=8082

# Ollama
spring.ai.ollama.base-url=http://localhost:11434

# Chat Model
spring.ai.ollama.chat.options.model=qwen2.5:1.5b

# Embedding Model
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.vectorstore.mariadb.initialize-schema=true

spring.datasource.url=jdbc:mariadb://localhost:3308/Spring_Ai
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver