spring.application.name=chapter-2

server.port=8081

#=====================================
#Gemini Congifuration
#=====================================
# Set this value using an environment variable or external secret store.
 spring.ai.google.genai.api-key=${Gemini_API_Key}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.ai.chat.client.enabled=flase